version: '3.3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: super_secret
      POSTGRES_DB: nerd_notes
